security:
    encoders:
        QoS\AdminBundle\Entity\Usuario:
            algorithm: bcrypt
            cost:      12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: QoSAdminBundle:Usuario}

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/*
            form_login:
                check_path: security_check
                login_path: login
                default_target_path: index
                csrf_parameter: _csrf_token
                intention:      authenticate
            logout:
                path:   logout
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/Presentacion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/Usuario$, roles: ROLE_ADMIN }
#        - { path: ^/super$, roles: ROLE_SUPER_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
