<?php

namespace QoS\MedicionesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MedicionInstitucionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicionInstitucionRepository extends EntityRepository
{
}
