<?php

namespace QoS\MedicionesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Paqueterepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaqueteRepository extends EntityRepository
{
}
